modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="suggestionproviderfix"
version="${file.jarVersion}"
displayName="Suggestion Provider Fix"
updateJSONURL="https://github.com/Harleyoc1/SuggestionProviderFix/blob/1.20/version_info.json?raw=true"
displayURL="https://www.curseforge.com/minecraft/mc-mods/suggestion-provider-fix"
credits=""
authors="Harley O'Connor"
description='''
A minor change to Minecraft's suggestion provider so that it auto-completes locations for all moded resources.
'''

[[dependencies.suggestionproviderfix]]
    modId="forge"
    mandatory=true
    versionRange="[47.0.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.suggestionproviderfix]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
